=== Ovanderb/WBA2/phase1/src/Aufgabe3/Aufgabe3c-Comments.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="comments">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="rezept">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="comment" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="username" type="xsd:string" />
                    <xsd:element name="userid" type="xsd:int" />
                    <xsd:element name="userpic" type="xsd:string" />
                    <xsd:element name="userexpirience">
                      <xsd:complexType>
                        <xsd:attribute name="value" type="xsd:int" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="commentdate" type="xsd:dateTime" />
                    <xsd:element name="commentwertung">
                      <xsd:complexType>
                        <xsd:attribute name="value" type="xsd:int" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="text" type="xsd:string" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:int" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="rezeptid" type="xsd:int" minOccurs="1" maxOccurs="1"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Ovanderb/WBA2/phase1/src/Aufgabe3/Samples/comment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<comments
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../Aufgabe3c-Comments.xsd'>
    <rezept rezeptid="1">
        <comment id="1">
            <username>Horst</username>
            <userid>20</userid>
            <userpic>/pic/user/20.jpg</userpic>
            <userexpirience value="3"></userexpirience>
            <commentdate>01.01.1900</commentdate>
            <commentwertung value="5"></commentwertung>
            <text>Hallo Welt</text>
        </comment>
        <comment id="2">
            <username>Klaus</username>
            <userid>21</userid>
            <userpic>/pic/user/21.jpg</userpic>
            <userexpirience value="2"></userexpirience>
            <commentdate>01.01.1901</commentdate>
            <commentwertung value="6"></commentwertung>
            <text>Foo Bar</text>
        </comment>
    </rezept>
    <rezept rezeptid="2">
        <comment id="1">
            <username>Hans</username>
            <userid>22</userid>
            <userpic>/pic/user/22.jpg</userpic>
            <userexpirience value="4"></userexpirience>
            <commentdate>01.01.1902</commentdate>
            <commentwertung value="1"></commentwertung>
            <text>GubbelGubbelGubbel</text>
        </comment>
    </rezept>

</comments>
