=== Ovanderb/WBA2/Phase1/src/Aufgabe3/Aufgabe3c.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="rezepte">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="rezept">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="photos" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="photo" minOccurs="0">
                      <xsd:complexType>
                        <xsd:attribute name="id" type="xsd:int" />
                        <xsd:attribute name="width" type="xsd:int" />
                        <xsd:attribute name="height" type="xsd:int" />
                        <xsd:attribute name="src" type="xsd:string" />
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="zutaten">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="zutat">
                      <xsd:complexType>
                        <xsd:attribute name="menge" type="xsd:int" />
                        <xsd:attribute name="einheit" type="xsd:string" />
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="schwierigkeit">
                <xsd:complexType>
                  <xsd:attribute name="value" type="xsd:string" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="arbeitszeit">
                <xsd:complexType>
                  <xsd:attribute name="value" type="xsd:int" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="brennwert">
                <xsd:complexType>
                  <xsd:attribute name="value" type="xsd:int" />
                  <xsd:attribute name="einheit" type="xsd:string" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="zubereitung" type="xsd:string" />
              <xsd:element name="socialnetworks">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="network">
                      <xsd:complexType>
                        <xsd:attribute name="name" type="xsd:string" />
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:int" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Ovanderb/WBA2/phase1/src/Aufgabe3/Samples/rezept.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezepte
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../Aufgabe3c.xsd'>
    <rezept id="1">
        <photos>
            <photo id="30" width="50" height="50" src="/pic/rezept/30.jpg">alternate</photo>
        </photos>
        <zutaten>
            <zutat menge="20" einheit="g">Butter</zutat>
            <zutat menge="2" einheit="Stk">Eier</zutat>
        </zutaten>
        <schwierigkeit value="schwer"></schwierigkeit>
        <arbeitszeit value="300"></arbeitszeit>
        <brennwert value="3000" einheit="kcal"></brennwert>
        <zubereitung>Alles in de Pott. Rühre. Fädisch.</zubereitung>
        <socialnetworks>
            <network name="facebook">6349374</network>
        </socialnetworks>
    </rezept>
    <rezept id="2">
        <photos>
            <photo id="31" width="50" height="50" src="/pic/rezept/31.jpg"></photo>
        </photos>
        <zutaten>
            <zutat menge="5" einheit="Stk">Eier</zutat>
            <zutat menge="500" einheit="g">Mehl</zutat>
        </zutaten>
        <schwierigkeit value="normal"></schwierigkeit>
        <arbeitszeit value="60"></arbeitszeit>
        <brennwert value="2500" einheit="kcal"></brennwert>
        <zubereitung>Ab in de Pott. Deckel druff. Schmoren. Fädisch</zubereitung>
        <socialnetworks>
            <network name="twitter">987594375</network>
        </socialnetworks>
    </rezept>
</rezepte>

=== Ovanderb/WBA2/phase1/src/Aufgabe3/Aufgabe3a-Rezept.xml
<?xml version="1.0" encoding="UTF-8"?>

<rezepte xmlns="http://www.gm.fh-koeln.de/~mi1242/wba2/rezepte"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="Aufgabe3c.xsd">
    <rezept id="345">
        <photos>
            <photo id="1" width="100" height="100" src="http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/31970-960x720-lenchen-s-schokoladenkuchen.jpg">beast354</photo>
            <photo id="2" width="100" height="100" src="http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/31970-960x720-lenchen-s-schokoladenkuchen.jpg">Klaus</photo>
            <photo id="3" width="100" height="100" src="http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/31970-960x720-lenchen-s-schokoladenkuchen.jpg">Hans</photo>
            <!-- usw. -->
        </photos>
        <zutaten>
            <zutat menge="200" einheit="g">Butter</zutat>
            <zutat menge="200" einheit="g">Zucker</zutat>
            <zutat menge="200" einheit="g">
                <link src="http://www.gm.fh-koeln.de/~mi1242/wba2/rezepte/zutaten/Schokolade">Schokolade</link>
                <link src="http://www.gm.fh-koeln.de/~mi1242/wba2/rezepte/zutaten/Blockschokolade">Blockschokolade</link>
            </zutat>
            <zutat menge="120" einheit="g">Mehl</zutat>
            <zutat menge="0.5" einheit="TL">Backpulver</zutat>
            <zutat menge="1" einheit="Pkt">Vanillezucker</zutat>
            <zutat menge="4" einheit="Stk">
                <link src="http://www.gm.fh-koeln.de/~mi1242/wba2/rezepte/zutaten/Ei">Ei(er)</link>
            </zutat>
            <!-- usw. -->
        </zutaten>
        <schwierigkeit value="normal" />
        <arbeitszeit value="60" />
        <brennwert value="295" einheit="kcal"/>
        <zubereitung>Butter und Schokolade im Wasserbad schmelzen. Eier trennen. Eiweiß steif schlagen. Eigelbe, Zucker und Vanillezucker verrühren. Geschmolzene Butter-Schokomasse hinzufügen und mischen. Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben. In eine gut gefettete Form geben.
Bei 180°Grad 40 – 50 Minuten backen.
        </zubereitung>
        <socialnetworks>
            <network name="facebook">723785992</network>
            <network name="googleplus">74478238</network>
            <network name="twitter">98347582</network>
            <!-- usw. -->
        </socialnetworks>
    </rezept>
</rezepte>
